### ISSUE TITLE
the file's size not match the size set by disk write payload

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#101]
create PhysicalMachineChaos in Chaos Mesh, the YAML config is below:

```YAML
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: write-payload
spec:
  action: disk-write-payload
  address:
    - http://172.16.112.130:31767
  uid: c11fa67a-ee03-4fab-9e85-77fdece0b1ff
  disk-write-payload:
    size: 100MB
    path: /tmp/test3
    payload_process_num: 5
```

the file's size should be 100MB, but in the host, the file's size is 19922944:
```bash
 ls -l /tmp/test3
-rw-r--r-- 1 root root 19922944 Oct 27 03:56 /tmp/test3
```
